# Generated by Django 5.2.17 on 2026-09-23 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('manager', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, default='admin', max_length=150)),
                ('username_env', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z_][A-Za-z0-9_]*$', 'Use an environment variable name.')])),
                ('password_env', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z_][A-Za-z0-9_]*$', 'Use an environment variable name.')])),
                ('ca_bundle', models.CharField(blank=True, max_length=500)),
                ('insecure', models.BooleanField(default=False)),
                ('workers', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('timeout', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('retries', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5)])),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Completed'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('testing', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='inventory.environment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField()),
                ('testing', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('imported', models.BooleanField(default=False)),
                ('summary', models.JSONField(default=dict)),
                ('report', models.JSONField()),
                ('html', models.TextField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='inventory.environment')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='inventory.auditjob')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='auditjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('environment',), name='one_active_audit_per_environment'),
        ),
    ]
