# Generated by Django 5.2.17 on 2026-09-23 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='password_ciphertext',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='password_env',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z_][A-Za-z0-9_]*$', 'Use an environment variable name.')]),
        ),
    ]
