# Generated by Django 5.2.17 on 2026-09-23 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_environment_password_ciphertext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditjob',
            name='progress_completed',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='auditjob',
            name='progress_stage',
            field=models.CharField(default='Waiting for an audit worker', max_length=150),
        ),
    ]
