# Generated by Django 5.2.17 on 2026-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditjob_progress_completed_auditjob_progress_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
