# Generated by Django 5.2.17 on 2026-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_snapshot_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditjob',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='next_sync_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(choices=[(0, 'Manual only'), (15, 'Every 15 minutes'), (30, 'Every 30 minutes'), (60, 'Every hour'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Daily'), (10080, 'Weekly')], default=60),
        ),
    ]
