# Generated by Django 5.2.17 on 2026-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auditjob_scheduled_environment_next_sync_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='ca_certificate',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='ca_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
