# Generated by Django 5.2.17 on 2026-09-23 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_environment_ca_certificate_environment_ca_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (50, '50'), (100, '100')], default=20)),
                ('report_page_size', models.PositiveSmallIntegerField(choices=[(25, '25'), (50, '50'), (100, '100')], default=25)),
                ('density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=15)),
                ('history_days', models.PositiveSmallIntegerField(choices=[(7, '7 days'), (30, '30 days'), (90, '90 days')], default=30)),
                ('refresh_seconds', models.PositiveSmallIntegerField(choices=[(5, '5 seconds'), (10, '10 seconds'), (30, '30 seconds'), (60, '60 seconds')], default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
