# Generated by Django 5.2.17 on 2026-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('snapshot_days', models.PositiveIntegerField(choices=[(0, 'Keep forever'), (91, '91 days'), (180, '180 days'), (365, '1 year'), (730, '2 years')], default=180)),
                ('testing_days', models.PositiveIntegerField(choices=[(0, 'Keep forever'), (7, '7 days'), (30, '30 days'), (91, '91 days')], default=30)),
                ('collection_days', models.PositiveIntegerField(choices=[(0, 'Keep forever'), (91, '91 days'), (180, '180 days'), (365, '1 year'), (730, '2 years')], default=180)),
                ('last_run', models.DateTimeField(editable=False, null=True)),
                ('deleted_snapshots', models.PositiveIntegerField(default=0, editable=False)),
                ('deleted_collections', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
