# Generated by Django 5.2.17 on 2026-09-23 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_retentionpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('stale_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8760)])),
                ('notify_failed', models.BooleanField(default=True)),
                ('notify_completed', models.BooleanField(default=True)),
                ('notify_coverage', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='date_format',
            field=models.CharField(choices=[('readable', '23 Sep 2026'), ('iso', '2026-09-23'), ('day-first', '23/09/2026'), ('month-first', '09/23/2026')], default='readable', max_length=12),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='interface_state',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='landing_page',
            field=models.CharField(choices=[('overview', 'Overview'), ('environment', 'Preferred environment'), ('activity', 'Firewall activity')], default='overview', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notifications_seen_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.environment'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='remember_menus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='remember_tables',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='text_size',
            field=models.CharField(choices=[('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=8),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('system', 'Follow system'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=8),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
