# Generated by Django 5.2.17 on 2026-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_workspacepolicy_userpreferences_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditjob',
            name='finished_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
