# Generated by Django 5.2.17 on 2026-09-24 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_auditjob_finished_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('path', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged')], default='open', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('present', models.BooleanField(default=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('evaluated_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inventory.environment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.snapshot')),
            ],
            options={
                'ordering': ['status', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FindingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.finding')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('environment', 'kind', 'path'), name='unique_environment_finding'),
        ),
    ]
