# Generated by Django 5.2.17 on 2026-09-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_finding_findingevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPFIXReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.PositiveBigIntegerField(default=0)),
                ('received', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IPFIXExporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(help_text='Exporter source IP as seen by the Docker receiver. One environment per address on this listener.', unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_received', models.DateTimeField(blank=True, null=True)),
                ('messages', models.PositiveBigIntegerField(default=0)),
                ('malformed', models.PositiveBigIntegerField(default=0)),
                ('data_sets', models.PositiveBigIntegerField(default=0)),
                ('templates', models.JSONField(blank=True, default=list)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipfix_exporters', to='inventory.environment')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
