# Generated by Django 5.2.17 on 2026-09-30 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_retire_traffic_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('outcome', models.CharField(db_index=True, default='success', max_length=20)),
                ('actor_id_text', models.CharField(blank=True, max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='auditjob',
            name='debug_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditjob',
            name='diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
