# Generated by Django 5.2.17 on 2026-09-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_initial_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotPresentation',
            fields=[
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='presentation', serialize=False, to='inventory.snapshot')),
                ('shell', models.JSONField()),
                ('tag_evidence', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80)),
                ('html', models.TextField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('view', models.CharField(max_length=20)),
                ('name', models.TextField()),
                ('sort_name', models.TextField()),
                ('compact', models.JSONField()),
                ('data', models.JSONField()),
                ('columns', models.JSONField()),
                ('sort_values', models.JSONField()),
                ('search_basic', models.TextField()),
                ('search_evidence', models.TextField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotRecordPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='inventory.snapshotpanel')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='inventory.snapshotrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='snapshotpanel',
            constraint=models.UniqueConstraint(fields=('snapshot', 'slug'), name='snapshot_panel_unique'),
        ),
        migrations.AddIndex(
            model_name='snapshotrecord',
            index=models.Index(fields=['snapshot', 'sort_name'], name='snapshot_record_name'),
        ),
        migrations.AddConstraint(
            model_name='snapshotrecord',
            constraint=models.UniqueConstraint(fields=('snapshot', 'ordinal'), name='snapshot_record_unique'),
        ),
        migrations.AddConstraint(
            model_name='snapshotrecordpanel',
            constraint=models.UniqueConstraint(fields=('panel', 'record'), name='snapshot_panel_record_unique'),
        ),
    ]
