# Generated by Django 5.2.17 on 2026-10-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_snapshot_presentation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['environment', '-generated_at', '-created_at'], name='snapshot_env_latest'),
        ),
    ]
