# Generated by Django 5.2.17 on 2026-10-01 05:52

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_snapshot_latest_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRevision',
            fields=[
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.environment')),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotHistoryData',
            fields=[
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='history_data', serialize=False, to='inventory.snapshot')),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=50)),
                ('revision', models.BigIntegerField(default=-1)),
                ('expires_at', models.DateTimeField(null=True)),
                ('metadata', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('anchor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.snapshot')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.environment')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAssessmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sort_name', models.TextField()),
                ('path', models.TextField()),
                ('rule_id_text', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='inventory.historyassessment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='historyassessment',
            constraint=models.UniqueConstraint(fields=('environment', 'cache_key'), name='history_assessment_unique'),
        ),
        migrations.AddIndex(
            model_name='historyassessmentrow',
            index=models.Index(fields=['assessment', 'sort_name'], name='history_row_name'),
        ),
        migrations.AddIndex(
            model_name='historyassessmentrow',
            index=models.Index(fields=['assessment', 'status'], name='history_row_status'),
        ),
    ]
