# Generated by Django 5.2.17 on 2026-10-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_efficient_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionStopRequest',
            fields=[
                ('job', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stop_request', serialize=False, to='inventory.auditjob')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('actor_id_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='auditjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Stopped')], default='queued', max_length=12),
        ),
    ]
