# Generated by Django 5.2.17 on 2026-10-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_collectionstoprequest_alter_auditjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_after', to='inventory.snapshot')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_before', to='inventory.snapshot')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='inventory.snapshotcomparison')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='snapshotcomparison',
            constraint=models.UniqueConstraint(fields=('before', 'after'), name='snapshot_comparison_pair'),
        ),
        migrations.AddIndex(
            model_name='snapshotcomparisonrow',
            index=models.Index(fields=['comparison', 'ordinal'], name='comparison_row_order'),
        ),
    ]
