# Generated by Django 5.2.17 on 2026-10-02 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_snapshotcomparison_snapshotcomparisonrow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditjob',
            index=models.Index(fields=['environment', '-created_at'], name='job_environment_recent'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['environment', 'present', 'status', 'name', 'id'], name='finding_environment_list'),
        ),
    ]
