# Generated by Django 5.2.17 on 2026-10-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auditjob_job_environment_recent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotCoverage',
            fields=[
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coverage_data', serialize=False, to='inventory.snapshot')),
                ('issue_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotCoverageIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('area', models.CharField(max_length=40)),
                ('name', models.TextField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.snapshotcoverage')),
            ],
            options={
                'ordering': ['ordinal'],
                'indexes': [models.Index(fields=['coverage', 'ordinal'], name='coverage_issue_order')],
            },
        ),
    ]
