# Generated by Django 5.2.17 on 2026-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_keycloakidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentionpolicy',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='testing_days',
            field=models.PositiveIntegerField(choices=[(0, 'Keep forever'), (7, '7 days'), (30, '30 days'), (91, '91 days')], default=7),
        ),
    ]
