# Generated by Django 5.2.17 on 2026-10-07 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_enable_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='global', max_length=40, unique=True)),
                ('zero_hits_days', models.PositiveIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(3650)])),
                ('empty_group_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3650)])),
                ('unused_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3650)])),
                ('empty_policy_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3650)])),
                ('disabled_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(3650)])),
                ('minimum_observations', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10000)])),
                ('maximum_gap_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8760)])),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotFindingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('kind', models.CharField(max_length=40)),
                ('assessment', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='finding',
            name='observation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finding',
            name='observation_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finding',
            name='observation_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='policy_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='finding',
            name='qualification',
            field=models.CharField(choices=[('observing', 'Observing'), ('eligible', 'Eligible for review'), ('insufficient', 'Insufficient evidence'), ('cleared', 'Condition cleared'), ('disabled', 'Qualification disabled')], default='insufficient', max_length=24),
        ),
        migrations.AddField(
            model_name='finding',
            name='qualification_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='finding',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='required_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['environment', 'qualification', 'kind', 'observation_days'], name='finding_qualification'),
        ),
        migrations.AddField(
            model_name='findingpolicy',
            name='environment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.environment'),
        ),
        migrations.AddField(
            model_name='snapshotfindingassessment',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_assessments', to='inventory.snapshot'),
        ),
        migrations.AddConstraint(
            model_name='snapshotfindingassessment',
            constraint=models.UniqueConstraint(fields=('snapshot', 'path', 'kind'), name='snapshot_finding_assessment'),
        ),
    ]
