# Generated by Django 5.2.17 on 2026-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_findingpolicy_snapshotfindingassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('issuer', models.URLField(blank=True, max_length=512)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('secret_ciphertext', models.TextField(blank=True)),
                ('ca_certificate', models.TextField(blank=True)),
                ('ca_bundle', models.CharField(blank=True, max_length=1024)),
                ('viewer_role', models.CharField(default='nsx-analyzer-viewer', max_length=255)),
                ('operator_role', models.CharField(default='nsx-analyzer-operator', max_length=255)),
                ('admin_role', models.CharField(default='nsx-analyzer-admin', max_length=255)),
            ],
        ),
    ]
