# Generated by Django 5.2.17 on 2026-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_keycloakconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakconfiguration',
            name='role_source',
            field=models.CharField(choices=[('realm', 'Realm roles'), ('client', 'Client roles')], default='realm', max_length=10),
        ),
    ]
