# Generated by Django 5.2.17 on 2026-10-08 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_userpreferences_notification_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('server_url', models.CharField(blank=True, max_length=512)),
                ('bind_dn', models.CharField(blank=True, max_length=1024)),
                ('secret_ciphertext', models.TextField(blank=True)),
                ('ca_certificate', models.TextField(blank=True)),
                ('user_base', models.CharField(blank=True, max_length=1024)),
                ('username_attribute', models.CharField(default='sAMAccountName', max_length=64)),
                ('identity_attribute', models.CharField(default='objectGUID', max_length=64)),
                ('viewer_group', models.CharField(blank=True, max_length=1024)),
                ('operator_group', models.CharField(blank=True, max_length=1024)),
                ('admin_group', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LDAPIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('directory', 'subject'), name='ldap_directory_subject_unique')],
            },
        ),
    ]
