# Generated by Django 5.2.17 on 2026-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_ldapconfiguration_ldapidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfiguration',
            name='secondary_ca_certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ldapconfiguration',
            name='secondary_server_url',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
