# Generated by Django 5.2.17 on 2026-10-08 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_ldapconfiguration_secondary_ca_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotFindingEvidenceIndex',
            fields=[
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.snapshot')),
                ('version', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FindingRecalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('kinds', models.JSONField(default=list)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('eligible', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finding_recalculation', to='inventory.environment')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotFindingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('path', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('zero_counter', models.BooleanField(default=False)),
                ('checked_at', models.CharField(blank=True, max_length=64)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_evidence', to='inventory.snapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'kind', 'path'), name='snapshot_finding_evidence_unique')],
            },
        ),
    ]
