# Generated by Django 5.2.17 on 2026-10-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_snapshotfindingevidenceindex_findingrecalculation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditjob',
            name='progress_stage',
            field=models.CharField(default='Waiting for a collection worker', max_length=150),
        ),
    ]
