# Generated by Django 5.2.17 on 2026-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_auditjob_progress_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='approvals',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='finding',
            name='change_ticket',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='finding',
            name='workflow_state',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('owner_review', 'Owner review'), ('second_review', 'Awaiting second approval'), ('ready', 'Ready for decommissioning'), ('decommissioned', 'Decommissioned'), ('rejected', 'Rejected')], db_index=True, default='unassigned', max_length=24),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='actor_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_reviews',
            field=models.BooleanField(default=True),
        ),
    ]
