# Generated by Django 5.2.17 on 2026-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_initialize_finding_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single approval'), (2, 'Two-person approval (four-eyes principle)')], default=2),
        ),
        migrations.AddField(
            model_name='workspacepolicy',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single approval'), (2, 'Two-person approval (four-eyes principle)')], default=2),
        ),
    ]
