# Generated by Django 5.2.17 on 2026-10-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def require_initial_password_rotation(apps, schema_editor):
    from django.contrib.auth.hashers import check_password
    alias = schema_editor.connection.alias
    User = apps.get_model('auth', 'User')
    Required = apps.get_model('inventory', 'InitialPasswordChange')
    for user in User.objects.using(alias).filter(username='admin', is_superuser=True).iterator():
        if check_password('NSXSecurityA!', user.password):
            Required.objects.using(alias).get_or_create(user_id=user.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0039_finding_required_approvals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialPasswordChange',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHeartbeat',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pod', models.CharField(max_length=255)),
                ('seen_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='snapshotcomparison',
            name='error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='snapshotcomparison',
            name='status',
            field=models.CharField(db_index=True, default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='snapshotrecord',
            name='relationships_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SnapshotRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('position', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='inventory.snapshotrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'section', 'position'), name='relationship_page_position')],
            },
        ),
        migrations.RunPython(require_initial_password_rotation, migrations.RunPython.noop),
    ]
